// dummyData.js

export const orders = [
    {
        id: '1',
        clientName: 'Client A',
        sku: 'SKU001',
        description: 'Product A',
        qty: 10,
        value: 100,
        status: 'Order Placed',
      },
      {
        id: '2',
        clientName: 'Client B',
        sku: 'SKU002',
        description: 'Product B',
        qty: 20,
        value: 200,
        status: 'No Issue',
      },
      {
        id: '3',
        clientName: 'Client C',
        sku: 'SKU003',
        description: 'Product C',
        qty: 15,
        value: 150,
        status: 'Order Shipped',
      },
      {
        id: '4',
        clientName: 'Client D',
        sku: 'SKU004',
        description: 'Product D',
        qty: 8,
        value: 80,
        status: 'Order Placed',
      },
      {
        id: '5',
        clientName: 'Client E',
        sku: 'SKU005',
        description: 'Product E',
        qty: 25,
        value: 250,
        status: 'No Issue',
      },
      {
        id: '6',
        clientName: 'Client F',
        sku: 'SKU006',
        description: 'Product F',
        qty: 12,
        value: 120,
        status: 'Order Shipped',
      },
      {
        id: '7',
        clientName: 'Client G',
        sku: 'SKU007',
        description: 'Product G',
        qty: 18,
        value: 180,
        status: 'Order Placed',
      },
      {
        id: '8',
        clientName: 'Client H',
        sku: 'SKU008',
        description: 'Product H',
        qty: 30,
        value: 300,
        status: 'No Issue',
      },
      {
        id: '9',
        clientName: 'Client I',
        sku: 'SKU009',
        description: 'Product I',
        qty: 5,
        value: 50,
        status: 'No Issue',
      },
      {
        id: '10',
        clientName: 'Client J',
        sku: 'SKU010',
        description: 'Product J',
        qty: 22,
        value: 220,
        status: 'Order Shipped',
      },
      {
        id: '11',
        clientName: 'Client K',
        sku: 'SKU011',
        description: 'Product K',
        qty: 7,
        value: 70,
        status: 'Order Placed',
      },
      {
        id: '12',
        clientName: 'Client L',
        sku: 'SKU012',
        description: 'Product L',
        qty: 14,
        value: 140,
        status: 'No Issue',
      },
      {
        id: '13',
        clientName: 'Client M',
        sku: 'SKU013',
        description: 'Product M',
        qty: 19,
        value: 190,
        status: 'No Issue',
      },
      {
        id: '14',
        clientName: 'Client N',
        sku: 'SKU014',
        description: 'Product N',
        qty: 9,
        value: 90,
        status: 'Order Shipped',
      },
      {
        id: '15',
        clientName: 'Client O',
        sku: 'SKU015',
        description: 'Product O',
        qty: 16,
        value: 160,
        status: 'Order Placed',
      },
      {
        id: '16',
        clientName: 'Client P',
        sku: 'SKU016',
        description: 'Product P',
        qty: 21,
        value: 210,
        status: 'No Issue',
      },
      {
        id: '17',
        clientName: 'Client Q',
        sku: 'SKU017',
        description: 'Product Q',
        qty: 11,
        value: 110,
        status: 'Order Shipped',
      },
      {
        id: '18',
        clientName: 'Client R',
        sku: 'SKU018',
        description: 'Product R',
        qty: 6,
        value: 60,
        status: 'Order Placed',
      },
      {
        id: '19',
        clientName: 'Client S',
        sku: 'SKU019',
        description: 'Product S',
        qty: 13,
        value: 130,
        status: 'No Issue',
      },
      {
        id: '20',
        clientName: 'Client T',
        sku: 'SKU020',
        description: 'Product T',
        qty: 17,
        value: 170,
        status: 'No Issue',
      },
    // Add more dummy data here
  ];
  